### ISSUE TITLE
image proxy 403, viewDiscussions is now viewForum

### ISSUE THREAD

**Issue by clarkwinkelmann** [FriendsOfFlarum/secure-https#16]
## Bug Report

**Current Behavior**
Non-admins can't use the image proxy.

**Screenshots**
![image](https://user-images.githubusercontent.com/5264300/126052751-dd670a9f-626c-4538-b94d-cab163f8c7a9.png)

**Possible solution(s)**
We use `viewDiscussions` permission which as renamed to `viewForum` in Flarum.

https://github.com/FriendsOfFlarum/secure-https/blob/03582954343c303a353ef95ae860f0e9808f8ea9/src/Api/Controllers/GetImageUrlController.php#L44

**Additional Context**
Report https://discuss.flarum.org/d/17771-friendsofflarum-secure-https/29

**Comment by ghost** [comment]
The proposed patch works for me, thanks!
