### ISSUE TITLE
The picture preview of the v17development/flarum-blog plug-in has not been proxied

### ISSUE THREAD

**Issue by huguadao** [FriendsOfFlarum/secure-https#24]
After installing and enabling the v17development/flarum-blog plug-in, the picture preview in the blog list and the header picture of the specific blog page (which is a picture with the list preview) are not proxied, and the picture source of http protocol is not displayed

![截屏2022-11-27 11.53.50](https://vip2.loli.io/2022/11/27/OCVSx8zIukR94yG.png)

![截屏2022-11-27 11.51.58](https://vip2.loli.io/2022/11/27/6GSBPkvw9zprI4D.png)

![截屏2022-11-27 12.00.20](https://vip2.loli.io/2022/11/27/uplQwGsTbFoZeyY.png)

**Comment by clarkwinkelmann** [comment]
This extension isn't able to automatically replace all images added by extensions. It needs specific code for every situation.

As it stands, I believe we only replace images inside of the post body. Nothing else.

This is the intended behavior until we decide to explicitly add support for Blog or other extensions.

I'm going to update the README to make this fact more clear.
