### ISSUE TITLE
HTTPS replacement doesn't work if bbcode extension is disabled

### ISSUE THREAD

**Issue by clarkwinkelmann** [FriendsOfFlarum/secure-https#25]
## Bug Report

**Current Behavior**
The original `http://` link is left completely untouched if Markdown is used while BBcode is disabled.

**Steps to Reproduce**
1. Disable proxy feature
2. Disable bbcode extension
3. Insert HTTP image using Markdown or AutoImage

**Expected Behavior**
Should be supported.

**Environment**
- Flarum version: 1.6.0
- Extension version: dev-main

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Possible solution(s)**
The problem is at

https://github.com/FriendsOfFlarum/secure-https/blob/de4866fb65bb00ba61498a9b446f0f6203595a38/src/ModifyContentHtml.php#L25

When the bbcode extension is disabled, images don't have a `title` attribute and the regex never matches anything.

**Comment by dsevillamartin** [comment]
BBCode seems to produce empty title HTML now. I still added the chance for it to be optional, but I don't think it's been an issue for a bit.
