### ISSUE TITLE
FoF Secure HTTPS breaks the image BBCode.

### ISSUE THREAD

**Issue by katosdev** [FriendsOfFlarum/secure-https#6]
When using FoF Secure HTTPS, BBCode Images do not work,

Steps to reproduce:

1. Enable Secure HTTPS
2. On ANY thread, embed a BBCode image as follows: [img]{URL}[/img]
3. Save the post, and check the image.

It's returning an image URL of : https://creatorswave.com/api/fof/secure-https/https%3A%2F%2Fwinaero.com%2Fblog%2Fwp-content%2Fuploads%2F2015%2F05%2FWindows-10-banner-logo-devs-04.png for example.

This leads to a broken image and also leads to the following error message on the site:
https://i.imgur.com/Y9YEkYo.png

**Comment by dsevillamartin** [comment]
~~Does that mean markdown images do work... ?~~ Saw your message on Discord, any kind of image embedding on a post.

Also, when you get the error when posting or whatever, please check the HTTP response and/or error logs to provide more information if possible.

**Comment by BigMinnie** [comment]
So 1 year and this bug is still here. When the extension is enabled it just does not show any pictures and it does not matter if it's already https or if it's http. And I'm not getting any error. 

And I'm using these two extension: 
- https://github.com/flarum/bbcode
- https://github.com/flarum/markdown

**Comment by katosdev** [comment]
@datitisev ^

**Comment by dsevillamartin** [comment]
This extension is currently not compatible with beta 13. Will look at the error when updating for it.

**Comment by karaok491** [comment]
@katosdev I've just tried to replicate this after updating this for beta 14, and all seems good now, based on your replication steps..
If possible, can you please confirm when you have a moment?

**Comment by katosdev** [comment]
> @katosdev I've just tried to replicate this after updating this for beta 14, and all seems good now, based on your replication steps..
> If possible, can you please confirm when you have a moment?

I'll have to pull this down and test - will try this ASAP :)

**Comment by BullyPanda** [comment]
So I tested on beta.14 and it does not show images inside bbcode or markdown code.
